### ISSUE TITLE
Make HostName optional parameter in LogDNA config call

### ISSUE THREAD

**Issue by halcharger** [iojancode/Serilog.Sinks.LogDNA#1]
Hi there, would it be possible to make hostName an optional parameter in the LogDNA extension call, I tried creating a PR but wasn't able to push the branch to github (possibly a fault on my side). The change is simple enough that I can include a screenshot of the diff, see below:

![image](https://user-images.githubusercontent.com/111745/109928566-3fc64e00-7cce-11eb-90b9-b923b3f448fb.png)

**Comment by iojancode** [comment]
done, 
Nuget version 1.0.3 https://www.nuget.org/packages/Serilog.Sinks.LogDNA/
